services:
  solution:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:password@db:5432/prod
      - MINIO_BUCKET_NAME=prod
      - MINIO_ENDPOINT=http://s3:9000
      - MINIO_ACCESS_KEY_ID=ZZxdWf3Q4Gu7Wk3hklOGDDYg
      - MINIO_SECRET_ACCESS_KEY=ZZ9ko24AA4OBk9nJTCRmQChHHnkxLVQ3kec6EebA
      - YANDEX_API_KEY=AQVNxrJLPoWtwQNQd3FgCjtbFJNS-usTfAtfrLyJ
      - YANDEX_FOLDER_ID=b1gip8uabjl2lsd3vfbf
    depends_on:
      - s3
      - db
      - redis
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prod
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.7-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3:
    image: bitnami/minio:2025.2.7
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=ZZxdWf3Q4Gu7Wk3hklOGDDYg
      - MINIO_ROOT_PASSWORD=ZZ9ko24AA4OBk9nJTCRmQChHHnkxLVQ3kec6EebA
      - MINIO_DEFAULT_BUCKETS=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s
